### ISSUE TITLE
npm errors during Create

### ISSUE THREAD

**Issue by nibzard** [daytonaio-experiments/starter-ai-chatbot#2]
![Screenshot from 2024-08-14 12-23-19](https://github.com/user-attachments/assets/7fb0b943-d503-4600-b820-3d35a8ada3c0)

**Comment by anuragkainth** [comment]
Hey, I have updated the devcontainer with `ubuntu:22.04` image and other feature related changes as suggested by Toma. Please test the repo again on your end. Issue seems resolved on my end.
